CREATE SEQUENCE  "UYUMSOFT"."ZFIND_SAGE_HESAPPLANI_ID"  MINVALUE 1 
MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE


CREATE TABLE "UYUMSOFT"."ZFIND_SAGE_HESAPPLANI" (
  "HESAPPLANI_ID" NUMBER NOT NULL,
  "ACC_CODE" VARCHAR2(50) NOT NULL,
  "HESAPPLANI_CODE" VARCHAR2(50) NOT NULL,
  PRIMARY KEY ("HESAPPLANI_ID")
)

INSERT INTO "UYUMSOFT"."ZFIND_SAGE_HESAPPLANI" ("HESAPPLANI_ID","ACC_CODE","HESAPPLANI_CODE") 
VALUES ("UYUMSOFT"."ZFIND_SAGE_HESAPPLANI_ID".NEXTVAL,'TTTTT','TTTTTT')